# Word lists for the spelling quiz game


# Unified word dictionary with grade levels, sight word classification, and definitions
word_dictionary = {
    # Grade 1 sight words
    "after": {"grade_levels": [1], "sight_word": True, "definition": "following in time or place"},
    "again": {"grade_levels": [1, 2], "sight_word": True, "definition": "once more; another time"},
    "an": {"grade_levels": [1], "sight_word": True, "definition": "used before vowel sounds instead of 'a'"},
    "any": {"grade_levels": [1], "sight_word": True, "definition": "one or some, regardless of which"},
    "as": {"grade_levels": [1], "sight_word": True, "definition": "to the same degree; while"},
    "ask": {"grade_levels": [1], "sight_word": True, "definition": "to request or inquire"},
    "by": {"grade_levels": [1], "sight_word": True, "definition": "near; through the action of"},
    "could": {"grade_levels": [1], "sight_word": True, "definition": "past tense of can; might be able to"},
    "every": {"grade_levels": [1], "sight_word": True, "definition": "each one without exception"},
    "fly": {"grade_levels": [1], "sight_word": True, "definition": "to move through air with wings"},
    "from": {"grade_levels": [1], "sight_word": True, "definition": "starting at a particular place or time"},
    "give": {"grade_levels": [1], "sight_word": True, "definition": "to hand over or present"},
    "going": {"grade_levels": [1], "sight_word": True, "definition": "moving or traveling"},
    "had": {"grade_levels": [1], "sight_word": True, "definition": "past tense of have"},
    "has": {"grade_levels": [1], "sight_word": True, "definition": "third person singular of have"},
    "her": {"grade_levels": [1], "sight_word": True, "definition": "belonging to a female person"},
    "him": {"grade_levels": [1], "sight_word": True, "definition": "male person as object of action"},
    "his": {"grade_levels": [1], "sight_word": True, "definition": "belonging to a male person"},
    "how": {"grade_levels": [1], "sight_word": True, "definition": "in what way or manner"},
    "just": {"grade_levels": [1], "sight_word": True, "definition": "exactly; only; recently"},
    "know": {"grade_levels": [1], "sight_word": True, "definition": "to be aware of or understand"},
    "let": {"grade_levels": [1], "sight_word": True, "definition": "to allow or permit"},
    "live": {"grade_levels": [1], "sight_word": True, "definition": "to be alive; to reside"},
    "may": {"grade_levels": [1], "sight_word": True, "definition": "expressing possibility or permission"},
    "of": {"grade_levels": [1], "sight_word": True, "definition": "belonging to; made from"},
    "old": {"grade_levels": [1], "sight_word": True, "definition": "having lived for many years"},
    "once": {"grade_levels": [1], "sight_word": True, "definition": "one time; formerly"},
    "open": {"grade_levels": [1, 4], "sight_word": True, "definition": "not closed; to unfasten"},
    "over": {"grade_levels": [1], "sight_word": True, "definition": "above; more than"},
    "put": {"grade_levels": [1], "sight_word": True, "definition": "to place in a position"},
    "round": {"grade_levels": [1], "sight_word": True, "definition": "circular in shape"},
    "some": {"grade_levels": [1], "sight_word": True, "definition": "an unspecified amount"},
    "stop": {"grade_levels": [1], "sight_word": True, "definition": "to cease moving or operating"},
    "take": {"grade_levels": [1], "sight_word": True, "definition": "to get hold of; to carry away"},
    "thank": {"grade_levels": [1], "sight_word": True, "definition": "to express gratitude"},
    "them": {"grade_levels": [1], "sight_word": True, "definition": "those people or things"},
    "then": {"grade_levels": [1], "sight_word": True, "definition": "at that time; next"},
    "think": {"grade_levels": [1], "sight_word": True, "definition": "to use one's mind; to believe"},
    "walk": {"grade_levels": [1], "sight_word": True, "definition": "to move on foot"},
    "were": {"grade_levels": [1], "sight_word": True, "definition": "past tense of 'are'"},
    "when": {"grade_levels": [1], "sight_word": True, "definition": "at what time"},
    
    # Grade 1 non-sight words
    "cat": {"grade_levels": [1], "sight_word": False, "definition": "a small furry pet animal that meows"},
    "dog": {"grade_levels": [1], "sight_word": False, "definition": "a four-legged pet animal that barks"},
    "sun": {"grade_levels": [1], "sight_word": False, "definition": "the bright star that gives Earth light"},
    "hat": {"grade_levels": [1], "sight_word": False, "definition": "clothing worn on the head"},
    "bed": {"grade_levels": [1], "sight_word": False, "definition": "furniture for sleeping"},
    "fish": {"grade_levels": [1], "sight_word": False, "definition": "animal that lives and breathes in water"},
    "run": {"grade_levels": [1], "sight_word": False, "definition": "to move quickly on foot"},
    "top": {"grade_levels": [1], "sight_word": False, "definition": "the highest part of something"},
    "man": {"grade_levels": [1], "sight_word": False, "definition": "an adult male human"},
    "pen": {"grade_levels": [1], "sight_word": False, "definition": "tool for writing with ink"},
    "red": {"grade_levels": [1], "sight_word": False, "definition": "the color of blood or roses"},
    "big": {"grade_levels": [1], "sight_word": False, "definition": "large in size"},
    "cup": {"grade_levels": [1], "sight_word": False, "definition": "small container for drinking"},
    "pig": {"grade_levels": [1], "sight_word": False, "definition": "farm animal that rolls in mud"},
    "log": {"grade_levels": [1], "sight_word": False, "definition": "piece of wood from a tree trunk"},
    "bag": {"grade_levels": [1], "sight_word": False, "definition": "container for carrying things"},
    "box": {"grade_levels": [1, 4], "sight_word": False, "definition": "container with flat sides and corners"},
    "jam": {"grade_levels": [1], "sight_word": False, "definition": "sweet spread made from fruit"},
    "milk": {"grade_levels": [1], "sight_word": False, "definition": "white liquid that comes from cows"},
    "rain": {"grade_levels": [1], "sight_word": False, "definition": "water falling from clouds"},
    "boat": {"grade_levels": [1], "sight_word": False, "definition": "vehicle for traveling on water"},
    "tree": {"grade_levels": [1], "sight_word": False, "definition": "large plant with trunk, branches, and leaves"},
    "corn": {"grade_levels": [1], "sight_word": False, "definition": "yellow grain that grows on tall stalks"},
    "cake": {"grade_levels": [1], "sight_word": False, "definition": "sweet baked dessert"},
    "blue": {"grade_levels": [1], "sight_word": False, "definition": "the color of the sky"},
    "jump": {"grade_levels": [1], "sight_word": False, "definition": "to push off the ground with both feet"},
    "sand": {"grade_levels": [1], "sight_word": False, "definition": "tiny pieces of rock found at beaches"},
    "rock": {"grade_levels": [1, 4], "sight_word": False, "definition": "hard piece of stone"},
    "shell": {"grade_levels": [1], "sight_word": False, "definition": "hard covering of sea creatures"},
    "grass": {"grade_levels": [1], "sight_word": False, "definition": "green plants that cover lawns"},
    "snow": {"grade_levels": [1], "sight_word": False, "definition": "frozen white flakes that fall from sky"},
    "light": {"grade_levels": [1], "sight_word": False, "definition": "brightness that helps us see"},
    "hand": {"grade_levels": [1], "sight_word": False, "definition": "part of body at end of arm with fingers"},
    "foot": {"grade_levels": [1], "sight_word": False, "definition": "part of body at end of leg for standing"},
    "bell": {"grade_levels": [1], "sight_word": False, "definition": "object that makes ringing sounds"},
    "ring": {"grade_levels": [1], "sight_word": False, "definition": "circular band worn on finger"},
    "toy": {"grade_levels": [1], "sight_word": False, "definition": "object children play with"},
    "farm": {"grade_levels": [1, 2], "sight_word": False, "definition": "place where crops and animals are raised"},
    "moon": {"grade_levels": [1], "sight_word": False, "definition": "round object that shines in night sky"},
    "bird": {"grade_levels": [1], "sight_word": False, "definition": "animal with wings and feathers that flies"},
    "apple": {"grade_levels": [1], "sight_word": False, "definition": "round red or green fruit"},
    "duck": {"grade_levels": [1], "sight_word": False, "definition": "water bird that quacks"},
    "frog": {"grade_levels": [1], "sight_word": False, "definition": "green animal that hops and lives near water"},
    "shoe": {"grade_levels": [1], "sight_word": False, "definition": "covering worn on feet"},
    "king": {"grade_levels": [2], "sight_word": False, "definition": "male ruler of a country"},
    "leaf": {"grade_levels": [1], "sight_word": False, "definition": "flat green part of a plant"},
    "nest": {"grade_levels": [1], "sight_word": False, "definition": "home that birds build for their eggs"},
    "star": {"grade_levels": [1], "sight_word": False, "definition": "bright point of light in night sky"},
    "wagon": {"grade_levels": [1], "sight_word": False, "definition": "vehicle with four wheels pulled by hand"},
    
    # Grade 2 sight words
    "always": {"grade_levels": [2], "sight_word": True, "definition": "at all times; forever"},
    "around": {"grade_levels": [2], "sight_word": True, "definition": "in a circle; near to"},
    "because": {"grade_levels": [2], "sight_word": True, "definition": "for the reason that"},
    "been": {"grade_levels": [2], "sight_word": True, "definition": "past participle of be"},
    "before": {"grade_levels": [2], "sight_word": True, "definition": "earlier than; in front of"},
    "best": {"grade_levels": [2], "sight_word": True, "definition": "of the highest quality"},
    "both": {"grade_levels": [2], "sight_word": True, "definition": "the two; one and the other"},
    "buy": {"grade_levels": [2], "sight_word": True, "definition": "to purchase with money"},
    "call": {"grade_levels": [2], "sight_word": True, "definition": "to shout; to telephone"},
    "cold": {"grade_levels": [2, 5], "sight_word": True, "definition": "having low temperature"},
    "does": {"grade_levels": [2], "sight_word": True, "definition": "third person singular of do"},
    "don't": {"grade_levels": [2], "sight_word": True, "definition": "contraction of do not"},
    "fast": {"grade_levels": [2], "sight_word": True, "definition": "moving with great speed"},
    "first": {"grade_levels": [2], "sight_word": True, "definition": "coming before all others"},
    "five": {"grade_levels": [2], "sight_word": True, "definition": "the number 5"},
    "found": {"grade_levels": [2], "sight_word": True, "definition": "past tense of find"},
    "gave": {"grade_levels": [2], "sight_word": True, "definition": "past tense of give"},
    "goes": {"grade_levels": [2], "sight_word": True, "definition": "third person singular of go"},
    "green": {"grade_levels": [2], "sight_word": True, "definition": "the color of grass and leaves"},
    "its": {"grade_levels": [2], "sight_word": True, "definition": "belonging to it"},
    "made": {"grade_levels": [2], "sight_word": True, "definition": "past tense of make"},
    "many": {"grade_levels": [2], "sight_word": True, "definition": "a large number of"},
    "off": {"grade_levels": [2], "sight_word": True, "definition": "away from; not on"},
    "or": {"grade_levels": [2], "sight_word": True, "definition": "indicating choice between options"},
    "pull": {"grade_levels": [2], "sight_word": True, "definition": "to draw toward oneself"},
    "read": {"grade_levels": [2], "sight_word": True, "definition": "to look at written text and understand"},
    "right": {"grade_levels": [2], "sight_word": True, "definition": "correct; opposite of left"},
    "sing": {"grade_levels": [2], "sight_word": True, "definition": "to make musical sounds with voice"},
    "sit": {"grade_levels": [2], "sight_word": True, "definition": "to rest on a chair or surface"},
    "sleep": {"grade_levels": [2], "sight_word": True, "definition": "to rest with eyes closed"},
    "tell": {"grade_levels": [2], "sight_word": True, "definition": "to speak or say something"},
    "their": {"grade_levels": [2], "sight_word": True, "definition": "belonging to them"},
    "these": {"grade_levels": [2], "sight_word": True, "definition": "plural of this; those here"},
    "those": {"grade_levels": [2], "sight_word": True, "definition": "plural of that; those there"},
    "upon": {"grade_levels": [2], "sight_word": True, "definition": "on top of"},
    "us": {"grade_levels": [2], "sight_word": True, "definition": "you and me; ourselves"},
    "use": {"grade_levels": [2], "sight_word": True, "definition": "to employ for a purpose"},
    "very": {"grade_levels": [2], "sight_word": True, "definition": "extremely; to a high degree"},
    "wash": {"grade_levels": [2], "sight_word": True, "definition": "to clean with water"},
    "which": {"grade_levels": [2], "sight_word": True, "definition": "what one; that particular"},
    "why": {"grade_levels": [2], "sight_word": True, "definition": "for what reason"},
    "wish": {"grade_levels": [2], "sight_word": True, "definition": "to hope for something"},
    "work": {"grade_levels": [2], "sight_word": True, "definition": "to do a job or task"},
    "would": {"grade_levels": [2], "sight_word": True, "definition": "expressing a conditional situation"},
    "write": {"grade_levels": [2], "sight_word": True, "definition": "to make letters or marks on paper"},
    "your": {"grade_levels": [2], "sight_word": True, "definition": "belonging to you"},
    
    # Grade 3 sight words
    "about": {"grade_levels": [3], "sight_word": True, "definition": "concerning; on the subject of"},
    "better": {"grade_levels": [3], "sight_word": True, "definition": "more good; improved"},
    "bring": {"grade_levels": [3], "sight_word": True, "definition": "to carry here; to take along"},
    "carry": {"grade_levels": [3], "sight_word": True, "definition": "to hold and move from place to place"},
    "clean": {"grade_levels": [3], "sight_word": True, "definition": "free from dirt"},
    "cut": {"grade_levels": [3], "sight_word": True, "definition": "to divide with sharp tool"},
    "done": {"grade_levels": [3], "sight_word": True, "definition": "finished; completed"},
    "draw": {"grade_levels": [3], "sight_word": True, "definition": "to make pictures with pencil"},
    "drink": {"grade_levels": [3], "sight_word": True, "definition": "to swallow liquid"},
    "eight": {"grade_levels": [3], "sight_word": True, "definition": "the number 8"},
    "fall": {"grade_levels": [3], "sight_word": True, "definition": "to drop down; autumn season"},
    "far": {"grade_levels": [3], "sight_word": True, "definition": "at a great distance"},
    "full": {"grade_levels": [3], "sight_word": True, "definition": "containing as much as possible"},
    "got": {"grade_levels": [3], "sight_word": True, "definition": "past tense of get"},
    "grow": {"grade_levels": [3], "sight_word": True, "definition": "to become bigger"},
    "hold": {"grade_levels": [3], "sight_word": True, "definition": "to grasp with hands"},
    "hot": {"grade_levels": [3], "sight_word": True, "definition": "having high temperature"},
    "hurt": {"grade_levels": [3], "sight_word": True, "definition": "to cause pain"},
    "if": {"grade_levels": [3], "sight_word": True, "definition": "supposing that; in case"},
    "keep": {"grade_levels": [3], "sight_word": True, "definition": "to continue having"},
    "kind": {"grade_levels": [3], "sight_word": True, "definition": "helpful and caring; type"},
    "laugh": {"grade_levels": [3], "sight_word": True, "definition": "to make sounds when amused"},
    "long": {"grade_levels": [3], "sight_word": True, "definition": "having great length"},
    "much": {"grade_levels": [3], "sight_word": True, "definition": "a large amount"},
    "myself": {"grade_levels": [3], "sight_word": True, "definition": "me, used for emphasis"},
    "never": {"grade_levels": [3], "sight_word": True, "definition": "not at any time"},
    "only": {"grade_levels": [3], "sight_word": True, "definition": "just; merely"},
    "own": {"grade_levels": [3], "sight_word": True, "definition": "belonging to oneself"},
    "pick": {"grade_levels": [3], "sight_word": True, "definition": "to choose; to gather"},
    "seven": {"grade_levels": [3], "sight_word": True, "definition": "the number 7"},
    "shall": {"grade_levels": [3], "sight_word": True, "definition": "will; used for future"},
    "show": {"grade_levels": [3], "sight_word": True, "definition": "to let someone see"},
    "six": {"grade_levels": [3, 4], "sight_word": True, "definition": "the number 6"},
    "small": {"grade_levels": [3], "sight_word": True, "definition": "little in size"},
    "start": {"grade_levels": [3], "sight_word": True, "definition": "to begin"},
    "ten": {"grade_levels": [3], "sight_word": True, "definition": "the number 10"},
    "today": {"grade_levels": [3], "sight_word": True, "definition": "this day"},
    "together": {"grade_levels": [3], "sight_word": True, "definition": "with each other"},
    "try": {"grade_levels": [3], "sight_word": True, "definition": "to attempt; to make effort"},
    "warm": {"grade_levels": [3], "sight_word": True, "definition": "having mild heat"},
    
    # Grade 4 sight words
    "area": {"grade_levels": [4], "sight_word": True, "definition": "space or region"},
    "ago": {"grade_levels": [4], "sight_word": True, "definition": "in the past"},
    "became": {"grade_levels": [4], "sight_word": True, "definition": "past tense of become"},
    "certain": {"grade_levels": [4], "sight_word": True, "definition": "sure; definite"},
    "color": {"grade_levels": [3], "sight_word": True, "definition": "what you see when light reflects"},
    "continue": {"grade_levels": [4], "sight_word": True, "definition": "to keep going"},
    "correct": {"grade_levels": [4], "sight_word": True, "definition": "right; without mistakes"},
    "course": {"grade_levels": [4], "sight_word": True, "definition": "path; class of study"},
    "decided": {"grade_levels": [4], "sight_word": True, "definition": "past tense of decide"},
    "dry": {"grade_levels": [4], "sight_word": True, "definition": "not wet"},
    "ever": {"grade_levels": [4], "sight_word": True, "definition": "at any time"},
    "fact": {"grade_levels": [4], "sight_word": True, "definition": "something that is true"},
    "finally": {"grade_levels": [4], "sight_word": True, "definition": "at last; in the end"},
    "friends": {"grade_levels": [4], "sight_word": True, "definition": "people you like and trust"},
    "half": {"grade_levels": [4], "sight_word": True, "definition": "one of two equal parts"},
    "heart": {"grade_levels": [4], "sight_word": True, "definition": "organ that pumps blood"},
    "horse": {"grade_levels": [4], "sight_word": True, "definition": "large animal used for riding"},
    "hundred": {"grade_levels": [4], "sight_word": True, "definition": "the number 100"},
    "knew": {"grade_levels": [4], "sight_word": True, "definition": "past tense of know"},
    "listen": {"grade_levels": [4], "sight_word": True, "definition": "to pay attention to sounds"},
    "mouth": {"grade_levels": [4], "sight_word": True, "definition": "opening in face for eating"},
    "music": {"grade_levels": [2], "sight_word": True, "definition": "organized sounds that are pleasing"},
    "order": {"grade_levels": [4], "sight_word": True, "definition": "arrangement; command"},
    "passed": {"grade_levels": [4], "sight_word": True, "definition": "went by; succeeded"},
    "piece": {"grade_levels": [4], "sight_word": True, "definition": "part of something"},
    "plan": {"grade_levels": [4], "sight_word": True, "definition": "scheme; to organize"},
    "poor": {"grade_levels": [4], "sight_word": True, "definition": "having little money"},
    "products": {"grade_levels": [4], "sight_word": True, "definition": "things that are made"},
    "remember": {"grade_levels": [4], "sight_word": True, "definition": "to recall from memory"},
    "room": {"grade_levels": [4], "sight_word": True, "definition": "space inside building"},
    "shown": {"grade_levels": [4], "sight_word": True, "definition": "past participle of show"},
    "slowly": {"grade_levels": [4], "sight_word": True, "definition": "not fast"},
    "stay": {"grade_levels": [4], "sight_word": True, "definition": "to remain in place"},
    "street": {"grade_levels": [4], "sight_word": True, "definition": "road in town or city"},
    "strong": {"grade_levels": [4], "sight_word": True, "definition": "having great power"},
    "surface": {"grade_levels": [4], "sight_word": True, "definition": "outside or top layer"},
    "system": {"grade_levels": [4, 6], "sight_word": True, "definition": "organized way of doing things"},
    "tail": {"grade_levels": [4], "sight_word": True, "definition": "part that sticks out from animal"},
    "teacher": {"grade_levels": [2, 3, 4], "sight_word": True, "definition": "person who instructs students"},
    "team": {"grade_levels": [4], "sight_word": True, "definition": "group working together"},
    "term": {"grade_levels": [4], "sight_word": True, "definition": "period of time; expression"},
    "themselves": {"grade_levels": [4], "sight_word": True, "definition": "they, used for emphasis"},
    "wait": {"grade_levels": [4], "sight_word": True, "definition": "to stay until something happens"},
    
    # Grade 5 sight words
    "afternoon": {"grade_levels": [3, 5], "sight_word": True, "definition": "time between noon and evening"},
    "amount": {"grade_levels": [5], "sight_word": True, "definition": "quantity; how much"},
    "am": {"grade_levels": [5], "sight_word": True, "definition": "first person singular of be"},
    "bill": {"grade_levels": [5], "sight_word": True, "definition": "statement of money owed"},
    "broken": {"grade_levels": [5], "sight_word": True, "definition": "damaged; not working"},
    "building": {"grade_levels": [5, 6], "sight_word": True, "definition": "structure with walls and roof"},
    "busy": {"grade_levels": [5], "sight_word": True, "definition": "having much to do"},
    "carefully": {"grade_levels": [5], "sight_word": True, "definition": "with great attention"},
    "circle": {"grade_levels": [2, 5], "sight_word": True, "definition": "round shape"},
    "clothes": {"grade_levels": [5], "sight_word": True, "definition": "things worn on body"},
    "company": {"grade_levels": [5], "sight_word": True, "definition": "business; group of people"},
    "condition": {"grade_levels": [5], "sight_word": True, "definition": "state of being"},
    "corner": {"grade_levels": [2, 5], "sight_word": True, "definition": "place where two lines meet"},
    "cover": {"grade_levels": [5], "sight_word": True, "definition": "to put something over"},
    "describe": {"grade_levels": [5, 8], "sight_word": True, "definition": "to tell about in detail"},
    "diagram": {"grade_levels": [5], "sight_word": True, "definition": "drawing that explains"},
    "direction": {"grade_levels": [4, 5, 7, 8], "sight_word": True, "definition": "way to go; guidance"},
    "energy": {"grade_levels": [4, 5, 7], "sight_word": True, "definition": "power to do work"},
    "engine": {"grade_levels": [5], "sight_word": True, "definition": "machine that makes things move"},
    "experiment": {"grade_levels": [5], "sight_word": True, "definition": "test to learn something"},
    "express": {"grade_levels": [5], "sight_word": True, "definition": "to show feelings or ideas"},
    "field": {"grade_levels": [5], "sight_word": True, "definition": "open area of land"},
    "figure": {"grade_levels": [5, 7], "sight_word": True, "definition": "number; shape; to solve"},
    "fraction": {"grade_levels": [4, 5, 7], "sight_word": True, "definition": "part of whole number"},
    "increase": {"grade_levels": [5, 8], "sight_word": True, "definition": "to make or become larger"},
    "instrument": {"grade_levels": [5, 8], "sight_word": True, "definition": "tool; device for making music"},
    "invented": {"grade_levels": [5], "sight_word": True, "definition": "created something new"},
    "kill": {"grade_levels": [5, 8], "sight_word": True, "definition": "to cause death"},
    "middle": {"grade_levels": [3], "sight_word": True, "definition": "center part"},
    "moment": {"grade_levels": [5, 8], "sight_word": True, "definition": "very short time"},
    "object": {"grade_levels": [5, 6, 8], "sight_word": True, "definition": "thing you can see and touch"},
    "perhaps": {"grade_levels": [5], "sight_word": True, "definition": "maybe; possibly"},
    "position": {"grade_levels": [4, 5], "sight_word": True, "definition": "place where something is"},
    "president": {"grade_levels": [4, 5], "sight_word": True, "definition": "leader of country or organization"},
    "problem": {"grade_levels": [4], "sight_word": True, "definition": "difficult situation to solve"},
    "quarter": {"grade_levels": [5], "sight_word": True, "definition": "one fourth; 25 cents"},
    "receive": {"grade_levels": [5], "sight_word": True, "definition": "to get something given"},
    "region": {"grade_levels": [5], "sight_word": True, "definition": "area of land"},
    "repeat": {"grade_levels": [5], "sight_word": True, "definition": "to do or say again"},
    "section": {"grade_levels": [5, 9], "sight_word": True, "definition": "part of something larger"},
    "sense": {"grade_levels": [5], "sight_word": True, "definition": "ability to see, hear, smell, taste, touch"},
    "serve": {"grade_levels": [5], "sight_word": True, "definition": "to help; to give food"},
    "solution": {"grade_levels": [5, 6], "sight_word": True, "definition": "answer to problem"},
    "special": {"grade_levels": [4], "sight_word": True, "definition": "different from usual"},
    "syllables": {"grade_levels": [5], "sight_word": True, "definition": "parts of spoken word"},
    "thousand": {"grade_levels": [5], "sight_word": True, "definition": "the number 1,000"},
    "village": {"grade_levels": [4, 5], "sight_word": True, "definition": "small town"},
    "weight": {"grade_levels": [5], "sight_word": True, "definition": "how heavy something is"},
    "written": {"grade_levels": [5, 6], "sight_word": True, "definition": "past participle of write"},
    "wrong": {"grade_levels": [5], "sight_word": True, "definition": "not correct"},
    
    # Grade 3 non-sight words
    "almost": {"grade_levels": [3], "sight_word": False, "definition": "nearly; not quite"},
    "animal": {"grade_levels": [3], "sight_word": False, "definition": "living creature that moves"},
    "basketball": {"grade_levels": [3], "sight_word": False, "definition": "sport played with ball and hoops"},
    "beautiful": {"grade_levels": [4], "sight_word": False, "definition": "very pretty to look at"},
    "birthday": {"grade_levels": [3], "sight_word": False, "definition": "day when person was born"},
    "bottle": {"grade_levels": [3], "sight_word": False, "definition": "container for liquids"},
    "brother": {"grade_levels": [3], "sight_word": False, "definition": "male sibling"},
    "butterfly": {"grade_levels": [3], "sight_word": False, "definition": "insect with colorful wings"},
    "camera": {"grade_levels": [3], "sight_word": False, "definition": "device for taking pictures"},
    "captain": {"grade_levels": [3, 6], "sight_word": False, "definition": "leader of ship or team"},
    "careful": {"grade_levels": [3], "sight_word": False, "definition": "paying attention to avoid mistakes"},
    "cheerful": {"grade_levels": [3], "sight_word": False, "definition": "happy and positive"},
    "children": {"grade_levels": [3], "sight_word": False, "definition": "young human beings"},
    "climate": {"grade_levels": [3], "sight_word": False, "definition": "weather patterns of region"},
    "cloudy": {"grade_levels": [3], "sight_word": False, "definition": "covered with clouds"},
    "country": {"grade_levels": [3], "sight_word": False, "definition": "nation; rural area"},
    "define": {"grade_levels": [3], "sight_word": True, "definition": "to explain meaning"},
    "decided": {"grade_levels": [3], "sight_word": False, "definition": "made choice"},
    "delicious": {"grade_levels": [3, 4], "sight_word": False, "definition": "tasting very good"},
    "different": {"grade_levels": [3, 6], "sight_word": False, "definition": "not the same"},
    "elephant": {"grade_levels": [3], "sight_word": False, "definition": "large gray animal with trunk"},
    "excited": {"grade_levels": [3], "sight_word": False, "definition": "feeling enthusiastic"},
    "family": {"grade_levels": [2, 3], "sight_word": False, "definition": "group of related people"},
    "favorite": {"grade_levels": [3, 4], "sight_word": False, "definition": "liked best"},
    "forgotten": {"grade_levels": [3], "sight_word": False, "definition": "not remembered"},
    "friendly": {"grade_levels": [3], "sight_word": False, "definition": "kind and helpful"},
    "garden": {"grade_levels": [3], "sight_word": False, "definition": "place where plants are grown"},
    "goldfish": {"grade_levels": [3], "sight_word": False, "definition": "small orange pet fish"},
    "happen": {"grade_levels": [2, 3], "sight_word": False, "definition": "to take place"},
    "important": {"grade_levels": [5], "sight_word": False, "definition": "having great value or meaning"},
    "inside": {"grade_levels": [3], "sight_word": False, "definition": "within; interior"},
    "jungle": {"grade_levels": [3], "sight_word": False, "definition": "thick tropical forest"},
    "library": {"grade_levels": [3, 4], "sight_word": False, "definition": "place with books to borrow"},
    "mountain": {"grade_levels": [4], "sight_word": False, "definition": "very high hill"},
    "neighbor": {"grade_levels": [3, 4], "sight_word": False, "definition": "person living nearby"},
    "outside": {"grade_levels": [3], "sight_word": False, "definition": "not inside; exterior"},
    "painter": {"grade_levels": [3], "sight_word": False, "definition": "person who paints pictures"},
    "parade": {"grade_levels": [3], "sight_word": False, "definition": "public procession"},
    "planet": {"grade_levels": [3, 6], "sight_word": False, "definition": "large object orbiting sun"},
    "pocket": {"grade_levels": [3], "sight_word": False, "definition": "small bag sewn in clothing"},
    "remember": {"grade_levels": [3], "sight_word": False, "definition": "to recall from memory"},
    "snowflake": {"grade_levels": [3], "sight_word": False, "definition": "single piece of falling snow"},
    "station": {"grade_levels": [3], "sight_word": False, "definition": "stopping place for trains"},
    "stronger": {"grade_levels": [3], "sight_word": False, "definition": "having more strength"},
    "summer": {"grade_levels": [2, 3], "sight_word": False, "definition": "warm season between spring and fall"},
    "weather": {"grade_levels": [3, 4], "sight_word": False, "definition": "conditions of atmosphere"},
    "window": {"grade_levels": [2, 3], "sight_word": False, "definition": "opening in wall with glass"},
    
    # Grade 4 non-sight words
    "adventure": {"grade_levels": [4, 5], "sight_word": False, "definition": "exciting and dangerous experience"},
    "apartment": {"grade_levels": [4], "sight_word": False, "definition": "set of rooms for living"},
    "argument": {"grade_levels": [4, 5], "sight_word": False, "definition": "disagreement with reasons"},
    "attention": {"grade_levels": [4, 5], "sight_word": False, "definition": "careful listening or watching"},
    "balance": {"grade_levels": [4], "sight_word": False, "definition": "even distribution of weight"},
    "believe": {"grade_levels": [4], "sight_word": False, "definition": "to think something is true"},
    "calendar": {"grade_levels": [4], "sight_word": False, "definition": "chart showing days and months"},
    "careless": {"grade_levels": [4], "sight_word": False, "definition": "not paying attention"},
    "category": {"grade_levels": [4, 5], "sight_word": False, "definition": "group of similar things"},
    "celebrate": {"grade_levels": [4], "sight_word": False, "definition": "to honor with special activities"},
    "comfortable": {"grade_levels": [4], "sight_word": False, "definition": "feeling at ease"},
    "community": {"grade_levels": [4, 5], "sight_word": False, "definition": "group of people living together"},
    "consider": {"grade_levels": [4, 5], "sight_word": False, "definition": "to think about carefully"},
    "curious": {"grade_levels": [4], "sight_word": False, "definition": "wanting to learn or know"},
    "data": {"grade_levels": [4], "sight_word": True, "definition": "facts and information"},
    "decimal": {"grade_levels": [4], "sight_word": False, "definition": "number with dot separating parts"},
    "discover": {"grade_levels": [4, 8], "sight_word": False, "definition": "to find out something new"},
    "education": {"grade_levels": [4], "sight_word": False, "definition": "process of learning"},
    "electric": {"grade_levels": [4], "sight_word": False, "definition": "powered by electricity"},
    "enormous": {"grade_levels": [4, 5], "sight_word": False, "definition": "extremely large"},
    "freedom": {"grade_levels": [4], "sight_word": False, "definition": "ability to act without restriction"},
    "gentle": {"grade_levels": [4], "sight_word": False, "definition": "kind and soft"},
    "history": {"grade_levels": [4, 5], "sight_word": False, "definition": "study of past events"},
    "imagine": {"grade_levels": [4], "sight_word": False, "definition": "to form picture in mind"},
    "include": {"grade_levels": [4, 5], "sight_word": False, "definition": "to contain as part"},
    "measurement": {"grade_levels": [4, 5], "sight_word": False, "definition": "act of measuring size"},
    "memory": {"grade_levels": [4, 5], "sight_word": False, "definition": "ability to remember"},
    "minute": {"grade_levels": [4], "sight_word": False, "definition": "60 seconds; very small"},
    "necessary": {"grade_levels": [4, 5], "sight_word": False, "definition": "required; essential"},
    "pattern": {"grade_levels": [4], "sight_word": False, "definition": "repeated design"},
    "population": {"grade_levels": [4], "sight_word": False, "definition": "number of people in area"},
    "practice": {"grade_levels": [4], "sight_word": False, "definition": "to do repeatedly to improve"},
    "promise": {"grade_levels": [4], "sight_word": False, "definition": "pledge to do something"},
    "purpose": {"grade_levels": [4], "sight_word": False, "definition": "reason for doing something"},
    "question": {"grade_levels": [3, 4], "sight_word": False, "definition": "sentence asking for information"},
    "sentence": {"grade_levels": [4], "sight_word": False, "definition": "group of words expressing thought"},
    "sincere": {"grade_levels": [4], "sight_word": False, "definition": "honest and genuine"},
    "wonderful": {"grade_levels": [4], "sight_word": False, "definition": "extremely good; amazing"},
    "zookeeper": {"grade_levels": [4], "sight_word": False, "definition": "person who cares for animals in zoo"},
    
    # Grade 5 non-sight words
    "accurate": {"grade_levels": [5, 6], "sight_word": False, "definition": "correct and exact"},
    "active": {"grade_levels": [5, 6], "sight_word": False, "definition": "busy; engaged in action"},
    "ancient": {"grade_levels": [5], "sight_word": False, "definition": "very old"},
    "apology": {"grade_levels": [5], "sight_word": False, "definition": "expression of regret"},
    "average": {"grade_levels": [5, 6], "sight_word": False, "definition": "typical; middle amount"},
    "behavior": {"grade_levels": [5, 6], "sight_word": False, "definition": "way of acting"},
    "biology": {"grade_levels": [5], "sight_word": False, "definition": "study of living things"},
    "calculate": {"grade_levels": [5, 6], "sight_word": False, "definition": "to work out using math"},
    "career": {"grade_levels": [5], "sight_word": False, "definition": "profession or job"},
    "challenge": {"grade_levels": [5, 6], "sight_word": False, "definition": "difficult task"},
    "character": {"grade_levels": [5, 6], "sight_word": False, "definition": "person in story; personality"},
    "chemical": {"grade_levels": [5], "sight_word": False, "definition": "substance made in laboratory"},
    "colony": {"grade_levels": [5, 6], "sight_word": False, "definition": "settlement in new land"},
    "communicate": {"grade_levels": [5, 6, 8], "sight_word": False, "definition": "to share information"},
    "compare": {"grade_levels": [5, 7, 8], "sight_word": False, "definition": "to examine similarities"},
    "complete": {"grade_levels": [5, 7], "sight_word": False, "definition": "finished; whole"},
    "comprehend": {"grade_levels": [5], "sight_word": False, "definition": "to understand"},
    "conclusion": {"grade_levels": [5, 6, 8], "sight_word": False, "definition": "end; final decision"},
    "conductor": {"grade_levels": [5], "sight_word": False, "definition": "person who leads orchestra"},
    "continent": {"grade_levels": [5, 6, 7], "sight_word": False, "definition": "large land mass"},
    "contrast": {"grade_levels": [5, 6, 7, 8], "sight_word": False, "definition": "to show differences"},
    "creative": {"grade_levels": [5, 8], "sight_word": False, "definition": "able to make new things"},
    "curiosity": {"grade_levels": [5], "sight_word": False, "definition": "desire to learn"},
    "decade": {"grade_levels": [5, 8], "sight_word": False, "definition": "period of ten years"},
    "decision": {"grade_levels": [5], "sight_word": False, "definition": "choice that is made"},
    "democracy": {"grade_levels": [5], "sight_word": False, "definition": "government by the people"},
    "develop": {"grade_levels": [5, 6, 8], "sight_word": False, "definition": "to grow or improve"},
    "distance": {"grade_levels": [5, 7], "sight_word": False, "definition": "space between two points"},
    "equation": {"grade_levels": [5, 6, 7], "sight_word": False, "definition": "mathematical statement"},
    "excellent": {"grade_levels": [5], "sight_word": False, "definition": "extremely good"},
    "familiar": {"grade_levels": [5], "sight_word": False, "definition": "well known"},
    "fortunate": {"grade_levels": [5], "sight_word": False, "definition": "lucky"},
    "function": {"grade_levels": [5, 6, 7, 9], "sight_word": False, "definition": "purpose; to work"},
    "geography": {"grade_levels": [5], "sight_word": False, "definition": "study of earth's features"},
    "government": {"grade_levels": [5, 7], "sight_word": False, "definition": "system of ruling country"},
    "grammar": {"grade_levels": [5, 7], "sight_word": False, "definition": "rules for using language"},
    "imagination": {"grade_levels": [5], "sight_word": False, "definition": "ability to create mental images"},
    "influence": {"grade_levels": [5, 6, 7, 8], "sight_word": False, "definition": "power to affect others"},
    "language": {"grade_levels": [5], "sight_word": False, "definition": "system of communication"},
    "organism": {"grade_levels": [5], "sight_word": False, "definition": "living being"},
    "paragraph": {"grade_levels": [5, 6], "sight_word": False, "definition": "group of sentences on one topic"},
    "restaurant": {"grade_levels": [5], "sight_word": False, "definition": "place where meals are served"},
    "xylophone": {"grade_levels": [5], "sight_word": False, "definition": "musical instrument with wooden bars"},
    
    # Grade 6 sight words
    "addition": {"grade_levels": [6], "sight_word": True, "definition": "the act of adding numbers"},
    "agree": {"grade_levels": [6], "sight_word": True, "definition": "to have the same opinion"},
    "allow": {"grade_levels": [6], "sight_word": True, "definition": "to permit or let happen"},
    "alphabet": {"grade_levels": [6], "sight_word": True, "definition": "the letters of a language"},
    "amaze": {"grade_levels": [6], "sight_word": True, "definition": "to surprise greatly"},
    "angle": {"grade_levels": [6], "sight_word": True, "definition": "space between two lines that meet"},
    "appear": {"grade_levels": [6], "sight_word": True, "definition": "to come into sight"},
    "arrive": {"grade_levels": [6], "sight_word": True, "definition": "to reach a place"},
    "axis": {"grade_levels": [6], "sight_word": True, "definition": "imaginary line through center"},
    "base": {"grade_levels": [6], "sight_word": True, "definition": "bottom part; foundation"},
    "belong": {"grade_levels": [6], "sight_word": True, "definition": "to be the property of"},
    "broad": {"grade_levels": [6], "sight_word": True, "definition": "wide; covering large area"},
    "cent": {"grade_levels": [6], "sight_word": True, "definition": "one hundredth of dollar"},
    "column": {"grade_levels": [6], "sight_word": True, "definition": "vertical row or pillar"},
    "compound": {"grade_levels": [6], "sight_word": True, "definition": "made of two or more parts"},
    "control": {"grade_levels": [6], "sight_word": True, "definition": "to direct or manage"},
    "cool": {"grade_levels": [6], "sight_word": True, "definition": "somewhat cold"},
    "cost": {"grade_levels": [6], "sight_word": True, "definition": "price paid for something"},
    "decide": {"grade_levels": [6], "sight_word": True, "definition": "to make choice"},
    "design": {"grade_levels": [6], "sight_word": True, "definition": "plan or pattern"},
    "division": {"grade_levels": [6], "sight_word": True, "definition": "act of dividing numbers"},
    "dollar": {"grade_levels": [6], "sight_word": True, "definition": "unit of money"},
    "entire": {"grade_levels": [6], "sight_word": True, "definition": "whole; complete"},
    "equal": {"grade_levels": [6], "sight_word": True, "definition": "same in amount or value"},
    "event": {"grade_levels": [6], "sight_word": True, "definition": "something that happens"},
    "exact": {"grade_levels": [6], "sight_word": True, "definition": "completely correct"},
    "expect": {"grade_levels": [6], "sight_word": True, "definition": "to think something will happen"},
    "explain": {"grade_levels": [6], "sight_word": True, "definition": "to make clear"},
    "famous": {"grade_levels": [6], "sight_word": True, "definition": "well known by many people"},
    "fig": {"grade_levels": [6], "sight_word": True, "definition": "sweet fruit"},
    "forward": {"grade_levels": [6], "sight_word": True, "definition": "toward the front"},
    "fresh": {"grade_levels": [6], "sight_word": True, "definition": "newly made; not old"},
    "guess": {"grade_levels": [6], "sight_word": True, "definition": "to form opinion without facts"},
    "heavy": {"grade_levels": [6], "sight_word": True, "definition": "having great weight"},
    "industry": {"grade_levels": [6], "sight_word": True, "definition": "business or manufacturing"},
    "level": {"grade_levels": [6], "sight_word": True, "definition": "height; degree"},
    "material": {"grade_levels": [6], "sight_word": True, "definition": "substance used to make things"},
    "modern": {"grade_levels": [6], "sight_word": True, "definition": "of the present time"},
    "nation": {"grade_levels": [6], "sight_word": True, "definition": "country"},
    "noun": {"grade_levels": [6], "sight_word": True, "definition": "word naming person, place, or thing"},
    "paint": {"grade_levels": [6], "sight_word": True, "definition": "colored liquid for covering surfaces"},
    "pair": {"grade_levels": [6], "sight_word": True, "definition": "set of two"},
    "plural": {"grade_levels": [6], "sight_word": True, "definition": "form meaning more than one"},
    "poem": {"grade_levels": [6], "sight_word": True, "definition": "piece of writing in verse"},
    "police": {"grade_levels": [6], "sight_word": True, "definition": "officers who keep order"},
    "power": {"grade_levels": [6], "sight_word": True, "definition": "strength; energy"},
    "produce": {"grade_levels": [6], "sight_word": True, "definition": "to make or create"},
    "properties": {"grade_levels": [6], "sight_word": True, "definition": "characteristics or qualities"},
    "protect": {"grade_levels": [6], "sight_word": True, "definition": "to keep safe"},
    "provide": {"grade_levels": [6], "sight_word": True, "definition": "to supply or give"},
    "raise": {"grade_levels": [6], "sight_word": True, "definition": "to lift up"},
    "represent": {"grade_levels": [6], "sight_word": True, "definition": "to stand for"},
    "root": {"grade_levels": [6], "sight_word": True, "definition": "part of plant underground"},
    "select": {"grade_levels": [6], "sight_word": True, "definition": "to choose"},
    "separate": {"grade_levels": [6], "sight_word": True, "definition": "to set apart"},
    "sharp": {"grade_levels": [6], "sight_word": True, "definition": "having cutting edge"},
    "silent": {"grade_levels": [6], "sight_word": True, "definition": "making no sound"},
    "similar": {"grade_levels": [6], "sight_word": True, "definition": "alike but not identical"},
    "space": {"grade_levels": [6], "sight_word": True, "definition": "empty area"},
    "straw": {"grade_levels": [6], "sight_word": True, "definition": "dried stalks of grain"},
    "symbol": {"grade_levels": [6], "sight_word": True, "definition": "sign representing something else"},
    "syllable": {"grade_levels": [6], "sight_word": True, "definition": "unit of spoken word"},
    "temperature": {"grade_levels": [6], "sight_word": True, "definition": "degree of heat or cold"},
    "though": {"grade_levels": [6], "sight_word": True, "definition": "even if; however"},
    "tiny": {"grade_levels": [6], "sight_word": True, "definition": "very small"},
    "triangle": {"grade_levels": [6], "sight_word": True, "definition": "shape with three sides"},
    "underline": {"grade_levels": [6], "sight_word": True, "definition": "to draw line under"},
    "valley": {"grade_levels": [6], "sight_word": True, "definition": "low area between hills"},
    "view": {"grade_levels": [6], "sight_word": True, "definition": "to look at"},
    "visit": {"grade_levels": [6], "sight_word": True, "definition": "to go see someone"},
    "wide": {"grade_levels": [6], "sight_word": True, "definition": "extending far from side to side"},
    "wild": {"grade_levels": [6], "sight_word": True, "definition": "living in nature"},
    "wire": {"grade_levels": [6], "sight_word": True, "definition": "thin metal thread"},
    "worth": {"grade_levels": [6], "sight_word": True, "definition": "having value of"},
    
    # Grade 7 sight words
    "active": {"grade_levels": [7], "sight_word": True, "definition": "busy; engaged in action"},
    "actual": {"grade_levels": [7], "sight_word": True, "definition": "real; existing"},
    "additional": {"grade_levels": [7], "sight_word": True, "definition": "extra; more"},
    "adjective": {"grade_levels": [7], "sight_word": True, "definition": "word describing noun"},
    "affect": {"grade_levels": [7], "sight_word": True, "definition": "to influence or change"},
    "allowance": {"grade_levels": [7], "sight_word": True, "definition": "amount permitted"},
    "announced": {"grade_levels": [7], "sight_word": True, "definition": "made known publicly"},
    "annual": {"grade_levels": [7], "sight_word": True, "definition": "happening every year"},
    "arrangement": {"grade_levels": [7], "sight_word": True, "definition": "way things are organized"},
    "audience": {"grade_levels": [7], "sight_word": True, "definition": "group of listeners or viewers"},
    "average": {"grade_levels": [7], "sight_word": True, "definition": "typical; middle amount"},
    "balance": {"grade_levels": [7], "sight_word": True, "definition": "even distribution of weight"},
    "barely": {"grade_levels": [7], "sight_word": True, "definition": "almost not; just"},
    "beyond": {"grade_levels": [7], "sight_word": True, "definition": "farther than"},
    "border": {"grade_levels": [7], "sight_word": True, "definition": "edge; boundary line"},
    "capital": {"grade_levels": [7], "sight_word": True, "definition": "main city of country"},
    "century": {"grade_levels": [7], "sight_word": True, "definition": "period of 100 years"},
    "character": {"grade_levels": [7], "sight_word": True, "definition": "person in story; personality"},
    "circumference": {"grade_levels": [7], "sight_word": True, "definition": "distance around circle"},
    "citizen": {"grade_levels": [7], "sight_word": True, "definition": "member of country"},
    "community": {"grade_levels": [7], "sight_word": True, "definition": "group of people living together"},
    "compare": {"grade_levels": [7], "sight_word": True, "definition": "to examine similarities"},
    "complete": {"grade_levels": [7], "sight_word": True, "definition": "finished; whole"},
    "compound": {"grade_levels": [7], "sight_word": True, "definition": "made of two or more parts"},
    "conclude": {"grade_levels": [7], "sight_word": True, "definition": "to end; to decide"},
    "connected": {"grade_levels": [7], "sight_word": True, "definition": "joined together"},
    "consider": {"grade_levels": [7], "sight_word": True, "definition": "to think about carefully"},
    "contain": {"grade_levels": [7], "sight_word": True, "definition": "to hold inside"},
    "continent": {"grade_levels": [7], "sight_word": True, "definition": "large land mass"},
    "contrast": {"grade_levels": [7], "sight_word": True, "definition": "to show differences"},
    "control": {"grade_levels": [7], "sight_word": True, "definition": "to direct or manage"},
    "coordinate": {"grade_levels": [7], "sight_word": True, "definition": "to organize together"},
    "current": {"grade_levels": [7], "sight_word": True, "definition": "happening now"},
    "definition": {"grade_levels": [7], "sight_word": True, "definition": "meaning of word"},
    "describe": {"grade_levels": [7], "sight_word": True, "definition": "to tell about in detail"},
    "determine": {"grade_levels": [7], "sight_word": True, "definition": "to decide or find out"},
    "difference": {"grade_levels": [7], "sight_word": True, "definition": "way things are not alike"},
    "direction": {"grade_levels": [7], "sight_word": True, "definition": "way to go; guidance"},
    "distance": {"grade_levels": [7], "sight_word": True, "definition": "space between two points"},
    "diverse": {"grade_levels": [7], "sight_word": True, "definition": "different; varied"},
    "energy": {"grade_levels": [7], "sight_word": True, "definition": "power to do work"},
    "equation": {"grade_levels": [7], "sight_word": True, "definition": "mathematical statement"},
    "evidence": {"grade_levels": [7], "sight_word": True, "definition": "proof or facts"},
    "example": {"grade_levels": [7], "sight_word": True, "definition": "sample; instance"},
    "examine": {"grade_levels": [7], "sight_word": True, "definition": "to look at carefully"},
    "factor": {"grade_levels": [7], "sight_word": True, "definition": "element that contributes"},
    "figure": {"grade_levels": [7], "sight_word": True, "definition": "number; shape; to solve"},
    "fraction": {"grade_levels": [7], "sight_word": True, "definition": "part of whole number"},
    "function": {"grade_levels": [7], "sight_word": True, "definition": "purpose; to work"},
    
    # Grade 8 sight words
    "ability": {"grade_levels": [8], "sight_word": True, "definition": "skill or talent"},
    "absence": {"grade_levels": [8], "sight_word": True, "definition": "state of being away"},
    "accept": {"grade_levels": [8], "sight_word": True, "definition": "to receive willingly"},
    "account": {"grade_levels": [8], "sight_word": True, "definition": "report; record"},
    "achievement": {"grade_levels": [8], "sight_word": True, "definition": "accomplishment"},
    "active": {"grade_levels": [8], "sight_word": True, "definition": "busy; engaged in action"},
    "addition": {"grade_levels": [8], "sight_word": True, "definition": "the act of adding"},
    "adventure": {"grade_levels": [8], "sight_word": True, "definition": "exciting experience"},
    "ambitious": {"grade_levels": [8], "sight_word": True, "definition": "having strong desire to succeed"},
    "analyze": {"grade_levels": [8], "sight_word": True, "definition": "to examine in detail"},
    "announce": {"grade_levels": [8], "sight_word": True, "definition": "to make known publicly"},
    "approach": {"grade_levels": [8], "sight_word": True, "definition": "to come near"},
    "arrange": {"grade_levels": [8], "sight_word": True, "definition": "to put in order"},
    "article": {"grade_levels": [8], "sight_word": True, "definition": "piece of writing"},
    "atmosphere": {"grade_levels": [8], "sight_word": True, "definition": "air surrounding earth"},
    "attention": {"grade_levels": [8], "sight_word": True, "definition": "careful listening or watching"},
    "audience": {"grade_levels": [8], "sight_word": True, "definition": "group of listeners"},
    "available": {"grade_levels": [8], "sight_word": True, "definition": "ready for use"},
    "beneath": {"grade_levels": [8], "sight_word": True, "definition": "under; below"},
    "benefit": {"grade_levels": [8], "sight_word": True, "definition": "advantage; help"},
    "calculate": {"grade_levels": [8], "sight_word": True, "definition": "to work out using math"},
    "cause": {"grade_levels": [8], "sight_word": True, "definition": "reason something happens"},
    "challenge": {"grade_levels": [8], "sight_word": True, "definition": "difficult task"},
    "citizen": {"grade_levels": [8], "sight_word": True, "definition": "member of country"},
    "collect": {"grade_levels": [8], "sight_word": True, "definition": "to gather together"},
    "combine": {"grade_levels": [8], "sight_word": True, "definition": "to join together"},
    "communicate": {"grade_levels": [8], "sight_word": True, "definition": "to share information"},
    "compare": {"grade_levels": [8], "sight_word": True, "definition": "to examine similarities"},
    "complex": {"grade_levels": [8], "sight_word": True, "definition": "complicated; difficult"},
    "conclusion": {"grade_levels": [8], "sight_word": True, "definition": "end; final decision"},
    "connection": {"grade_levels": [8], "sight_word": True, "definition": "link between things"},
    "consequence": {"grade_levels": [8], "sight_word": True, "definition": "result of action"},
    "constant": {"grade_levels": [8], "sight_word": True, "definition": "continuing without change"},
    "construct": {"grade_levels": [8], "sight_word": True, "definition": "to build"},
    "context": {"grade_levels": [8], "sight_word": True, "definition": "circumstances surrounding event"},
    "contrast": {"grade_levels": [8], "sight_word": True, "definition": "to show differences"},
    "contribute": {"grade_levels": [8], "sight_word": True, "definition": "to give or help"},
    "creative": {"grade_levels": [8], "sight_word": True, "definition": "able to make new things"},
    "culture": {"grade_levels": [8], "sight_word": True, "definition": "way of life of group"},
    "debate": {"grade_levels": [8], "sight_word": True, "definition": "formal discussion"},
    "decade": {"grade_levels": [8], "sight_word": True, "definition": "period of ten years"},
    "declare": {"grade_levels": [8], "sight_word": True, "definition": "to state firmly"},
    "demonstrate": {"grade_levels": [8], "sight_word": True, "definition": "to show clearly"},
    "describe": {"grade_levels": [8], "sight_word": True, "definition": "to tell about in detail"},
    "develop": {"grade_levels": [8], "sight_word": True, "definition": "to grow or improve"},
    "difference": {"grade_levels": [8], "sight_word": True, "definition": "way things are not alike"},
    "direction": {"grade_levels": [8], "sight_word": True, "definition": "way to go; guidance"},
    "discover": {"grade_levels": [8], "sight_word": True, "definition": "to find out something new"},
    "discussion": {"grade_levels": [8], "sight_word": True, "definition": "conversation about topic"},
    
    # Grade 6 non-sight words
    "abundant": {"grade_levels": [6], "sight_word": False, "definition": "existing in large amounts"},
    "accurately": {"grade_levels": [6], "sight_word": False, "definition": "in correct and exact way"},
    "adaptation": {"grade_levels": [6], "sight_word": False, "definition": "change to fit environment"},
    "ambition": {"grade_levels": [6], "sight_word": False, "definition": "strong desire to succeed"},
    "analysis": {"grade_levels": [6], "sight_word": False, "definition": "detailed examination"},
    "ancestor": {"grade_levels": [6], "sight_word": False, "definition": "family member from past"},
    "apparent": {"grade_levels": [6], "sight_word": False, "definition": "clearly seen or understood"},
    "approach": {"grade_levels": [6], "sight_word": False, "definition": "way of dealing with something"},
    "atmosphere": {"grade_levels": [6], "sight_word": False, "definition": "air surrounding earth"},
    "attribute": {"grade_levels": [6], "sight_word": False, "definition": "characteristic or quality"},
    "barrier": {"grade_levels": [6], "sight_word": False, "definition": "something that blocks"},
    "beneficial": {"grade_levels": [6], "sight_word": False, "definition": "helpful; good for you"},
    "calculate": {"grade_levels": [6], "sight_word": False, "definition": "to work out using math"},
    "campaign": {"grade_levels": [6], "sight_word": False, "definition": "organized effort"},
    "category": {"grade_levels": [6], "sight_word": False, "definition": "group of similar things"},
    "civilization": {"grade_levels": [6], "sight_word": False, "definition": "advanced human society"},
    "collapse": {"grade_levels": [6], "sight_word": False, "definition": "to fall down suddenly"},
    "colony": {"grade_levels": [6], "sight_word": False, "definition": "settlement in new land"},
    "communicate": {"grade_levels": [6], "sight_word": False, "definition": "to share information"},
    "competition": {"grade_levels": [6], "sight_word": False, "definition": "contest between rivals"},
    "conclusion": {"grade_levels": [6], "sight_word": False, "definition": "end; final decision"},
    "consequence": {"grade_levels": [6], "sight_word": False, "definition": "result of action"},
    "construct": {"grade_levels": [6], "sight_word": False, "definition": "to build"},
    "contrast": {"grade_levels": [6], "sight_word": False, "definition": "to show differences"},
    "convert": {"grade_levels": [6], "sight_word": False, "definition": "to change from one form to another"},
    "critical": {"grade_levels": [6], "sight_word": False, "definition": "very important"},
    "culture": {"grade_levels": [6], "sight_word": False, "definition": "way of life of group"},
    "declare": {"grade_levels": [6], "sight_word": False, "definition": "to state firmly"},
    "determine": {"grade_levels": [6], "sight_word": False, "definition": "to decide or find out"},
    "develop": {"grade_levels": [6], "sight_word": False, "definition": "to grow or improve"},
    "discovery": {"grade_levels": [6], "sight_word": False, "definition": "finding something new"},
    "diversity": {"grade_levels": [6], "sight_word": False, "definition": "variety; difference"},
    "efficient": {"grade_levels": [6], "sight_word": False, "definition": "working well without waste"},
    "environment": {"grade_levels": [6], "sight_word": False, "definition": "surroundings"},
    "equation": {"grade_levels": [6], "sight_word": False, "definition": "mathematical statement"},
    "evidence": {"grade_levels": [6], "sight_word": False, "definition": "proof or facts"},
    "experiment": {"grade_levels": [6], "sight_word": False, "definition": "test to learn something"},
    "expression": {"grade_levels": [6], "sight_word": False, "definition": "way of showing feeling"},
    "formation": {"grade_levels": [6], "sight_word": False, "definition": "way something is formed"},
    "function": {"grade_levels": [6], "sight_word": False, "definition": "purpose; to work"},
    "gravity": {"grade_levels": [6], "sight_word": False, "definition": "force pulling objects down"},
    "heritage": {"grade_levels": [6], "sight_word": False, "definition": "traditions passed down"},
    "importance": {"grade_levels": [6], "sight_word": False, "definition": "quality of being important"},
    "independent": {"grade_levels": [6], "sight_word": False, "definition": "free; not controlled by others"},
    "influence": {"grade_levels": [6], "sight_word": False, "definition": "power to affect others"},
    "magnificent": {"grade_levels": [6], "sight_word": False, "definition": "extremely beautiful or impressive"},
    "molecule": {"grade_levels": [6], "sight_word": False, "definition": "smallest unit of substance"},
    "narrative": {"grade_levels": [6], "sight_word": False, "definition": "story or account"},
    "particular": {"grade_levels": [6], "sight_word": False, "definition": "specific; special"},
    "perspective": {"grade_levels": [6], "sight_word": False, "definition": "point of view"},
    "reaction": {"grade_levels": [6], "sight_word": False, "definition": "response to something"},
    "tremendous": {"grade_levels": [6], "sight_word": False, "definition": "very large; enormous"},
    "vocabulary": {"grade_levels": [6], "sight_word": False, "definition": "collection of words known by person"},
    
    # Grade 7 non-sight words
    "achievement": {"grade_levels": [7], "sight_word": False, "definition": "accomplishment"},
    "adaptation": {"grade_levels": [7], "sight_word": False, "definition": "change to fit environment"},
    "advantage": {"grade_levels": [7], "sight_word": False, "definition": "benefit; favorable position"},
    "ambiguous": {"grade_levels": [7], "sight_word": False, "definition": "having more than one meaning"},
    "analyze": {"grade_levels": [7], "sight_word": False, "definition": "to examine in detail"},
    "apparatus": {"grade_levels": [7], "sight_word": False, "definition": "equipment for specific purpose"},
    "application": {"grade_levels": [7], "sight_word": False, "definition": "practical use; request"},
    "argumentative": {"grade_levels": [7], "sight_word": False, "definition": "presenting reasons for opinion"},
    "artificial": {"grade_levels": [7], "sight_word": False, "definition": "made by humans, not natural"},
    "assumption": {"grade_levels": [7], "sight_word": False, "definition": "something accepted as true"},
    "atmosphere": {"grade_levels": [7], "sight_word": False, "definition": "air surrounding earth"},
    "behavioral": {"grade_levels": [7], "sight_word": False, "definition": "relating to behavior"},
    "calculation": {"grade_levels": [7], "sight_word": False, "definition": "mathematical computation"},
    "capability": {"grade_levels": [7], "sight_word": False, "definition": "ability to do something"},
    "category": {"grade_levels": [7], "sight_word": False, "definition": "group of similar things"},
    "chronological": {"grade_levels": [7], "sight_word": False, "definition": "arranged in time order"},
    "circumstance": {"grade_levels": [7], "sight_word": False, "definition": "condition or situation"},
    "collaboration": {"grade_levels": [7], "sight_word": False, "definition": "working together"},
    "colleague": {"grade_levels": [7], "sight_word": False, "definition": "fellow worker"},
    "complexity": {"grade_levels": [7], "sight_word": False, "definition": "state of being complicated"},
    "component": {"grade_levels": [7], "sight_word": False, "definition": "part of larger whole"},
    "comprehensive": {"grade_levels": [7], "sight_word": False, "definition": "including everything"},
    "consequence": {"grade_levels": [7], "sight_word": False, "definition": "result of action"},
    "constellation": {"grade_levels": [7], "sight_word": False, "definition": "group of stars"},
    "contamination": {"grade_levels": [7], "sight_word": False, "definition": "making impure or dirty"},
    "criteria": {"grade_levels": [7], "sight_word": False, "definition": "standards for judging"},
    "debate": {"grade_levels": [7], "sight_word": False, "definition": "formal discussion"},
    "demonstration": {"grade_levels": [7], "sight_word": False, "definition": "showing how something works"},
    "destination": {"grade_levels": [7], "sight_word": False, "definition": "place where someone is going"},
    "developed": {"grade_levels": [7], "sight_word": False, "definition": "grown or improved"},
    "discipline": {"grade_levels": [7], "sight_word": False, "definition": "field of study; self-control"},
    "distribute": {"grade_levels": [7], "sight_word": False, "definition": "to give out"},
    "efficient": {"grade_levels": [7], "sight_word": False, "definition": "working well without waste"},
    "elaborate": {"grade_levels": [7], "sight_word": False, "definition": "detailed; to explain more"},
    "elementary": {"grade_levels": [7], "sight_word": False, "definition": "basic; simple"},
    "environmental": {"grade_levels": [7], "sight_word": False, "definition": "relating to surroundings"},
    "essential": {"grade_levels": [7], "sight_word": False, "definition": "absolutely necessary"},
    "evaluate": {"grade_levels": [7], "sight_word": False, "definition": "to judge the value of"},
    "evolution": {"grade_levels": [7], "sight_word": False, "definition": "gradual change over time"},
    "foundation": {"grade_levels": [7], "sight_word": False, "definition": "base or basis"},
    "hypothesis": {"grade_levels": [7], "sight_word": False, "definition": "educated guess for testing"},
    "illustration": {"grade_levels": [7], "sight_word": False, "definition": "picture; example"},
    "influence": {"grade_levels": [7], "sight_word": False, "definition": "power to affect others"},
    "interpretation": {"grade_levels": [7], "sight_word": False, "definition": "explanation of meaning"},
    "literature": {"grade_levels": [7], "sight_word": False, "definition": "written works of art"},
    "magnitude": {"grade_levels": [7], "sight_word": False, "definition": "size or extent"},
    "opportunity": {"grade_levels": [7, 8], "sight_word": False, "definition": "favorable time for action"},
    "phenomenon": {"grade_levels": [7], "sight_word": False, "definition": "observable event"},
    "significance": {"grade_levels": [7], "sight_word": False, "definition": "importance; meaning"},
    
    # Grade 8 non-sight words
    "adaptation": {"grade_levels": [8], "sight_word": False, "definition": "change to fit environment"},
    "advantageous": {"grade_levels": [8], "sight_word": False, "definition": "beneficial; helpful"},
    "agriculture": {"grade_levels": [8], "sight_word": False, "definition": "farming and growing crops"},
    "analysis": {"grade_levels": [8], "sight_word": False, "definition": "detailed examination"},
    "anticipate": {"grade_levels": [8], "sight_word": False, "definition": "to expect or predict"},
    "apparatus": {"grade_levels": [8], "sight_word": False, "definition": "equipment for specific purpose"},
    "approximate": {"grade_levels": [8], "sight_word": False, "definition": "close to exact; estimate"},
    "architecture": {"grade_levels": [8], "sight_word": False, "definition": "design of buildings"},
    "argumentative": {"grade_levels": [8], "sight_word": False, "definition": "presenting reasons for opinion"},
    "articulate": {"grade_levels": [8], "sight_word": False, "definition": "to express clearly"},
    "assertive": {"grade_levels": [8], "sight_word": False, "definition": "confident and direct"},
    "association": {"grade_levels": [8], "sight_word": False, "definition": "connection or organization"},
    "attribute": {"grade_levels": [8], "sight_word": False, "definition": "characteristic or quality"},
    "authentic": {"grade_levels": [8], "sight_word": False, "definition": "genuine; real"},
    "biological": {"grade_levels": [8], "sight_word": False, "definition": "relating to living things"},
    "circumstance": {"grade_levels": [8], "sight_word": False, "definition": "condition or situation"},
    "collaboration": {"grade_levels": [8], "sight_word": False, "definition": "working together"},
    "commitment": {"grade_levels": [8], "sight_word": False, "definition": "dedication; promise"},
    "component": {"grade_levels": [8], "sight_word": False, "definition": "part of larger whole"},
    "comprehensive": {"grade_levels": [8], "sight_word": False, "definition": "including everything"},
    "conceptual": {"grade_levels": [8], "sight_word": False, "definition": "relating to ideas"},
    "conservation": {"grade_levels": [8], "sight_word": False, "definition": "protection of natural resources"},
    "consideration": {"grade_levels": [8], "sight_word": False, "definition": "careful thought"},
    "contamination": {"grade_levels": [8], "sight_word": False, "definition": "making impure or dirty"},
    "cooperation": {"grade_levels": [8], "sight_word": False, "definition": "working together"},
    "correspondence": {"grade_levels": [8], "sight_word": False, "definition": "letters; similarity"},
    "definition": {"grade_levels": [8], "sight_word": False, "definition": "meaning of word"},
    "description": {"grade_levels": [8], "sight_word": False, "definition": "account of characteristics"},
    "distribution": {"grade_levels": [8], "sight_word": False, "definition": "giving out; spread"},
    "efficiency": {"grade_levels": [8], "sight_word": False, "definition": "working well without waste"},
    "elaboration": {"grade_levels": [8], "sight_word": False, "definition": "detailed explanation"},
    "environmental": {"grade_levels": [8], "sight_word": False, "definition": "relating to surroundings"},
    "evaluation": {"grade_levels": [8], "sight_word": False, "definition": "assessment of value"},
    "exaggeration": {"grade_levels": [8], "sight_word": False, "definition": "making something seem larger"},
    "explanation": {"grade_levels": [8], "sight_word": False, "definition": "making something clear"},
    "foundation": {"grade_levels": [8], "sight_word": False, "definition": "base or basis"},
    "hypothesis": {"grade_levels": [8], "sight_word": False, "definition": "educated guess for testing"},
    "illustration": {"grade_levels": [8], "sight_word": False, "definition": "picture; example"},
    "independent": {"grade_levels": [8], "sight_word": False, "definition": "free; not controlled by others"},
    "influence": {"grade_levels": [8], "sight_word": False, "definition": "power to affect others"},
    "interpretation": {"grade_levels": [8], "sight_word": False, "definition": "explanation of meaning"},
    "justification": {"grade_levels": [8], "sight_word": False, "definition": "reason for action"},
    "measurement": {"grade_levels": [8], "sight_word": False, "definition": "act of measuring size"},
    "methodology": {"grade_levels": [8], "sight_word": False, "definition": "system of methods"},
    "organization": {"grade_levels": [8], "sight_word": False, "definition": "arranged structure"},
    "perspective": {"grade_levels": [8], "sight_word": False, "definition": "point of view"},
    "phenomenon": {"grade_levels": [8], "sight_word": False, "definition": "observable event"},
    "preparation": {"grade_levels": [8], "sight_word": False, "definition": "getting ready"},
    "scientific": {"grade_levels": [8], "sight_word": False, "definition": "relating to science"},
    "significance": {"grade_levels": [8], "sight_word": False, "definition": "importance; meaning"},
    "theoretical": {"grade_levels": [8], "sight_word": False, "definition": "based on theory, not practice"},
    
    # Grade 9 sight words
    "abstract": {"grade_levels": [9], "sight_word": True, "definition": "existing in thought; not concrete"},
    "analyze": {"grade_levels": [9], "sight_word": True, "definition": "to examine in detail"},
    "approach": {"grade_levels": [9], "sight_word": True, "definition": "to come near; method"},
    "argument": {"grade_levels": [9], "sight_word": True, "definition": "disagreement with reasons"},
    "assume": {"grade_levels": [9], "sight_word": True, "definition": "to suppose without proof"},
    "category": {"grade_levels": [9], "sight_word": True, "definition": "group of similar things"},
    "circumstance": {"grade_levels": [9], "sight_word": True, "definition": "condition or situation"},
    "clarify": {"grade_levels": [9], "sight_word": True, "definition": "to make clear"},
    "coherent": {"grade_levels": [9], "sight_word": True, "definition": "logical and consistent"},
    "complexity": {"grade_levels": [9], "sight_word": True, "definition": "state of being complicated"},
    "component": {"grade_levels": [9], "sight_word": True, "definition": "part of larger whole"},
    "concept": {"grade_levels": [9], "sight_word": True, "definition": "general idea"},
    "conclusion": {"grade_levels": [9], "sight_word": True, "definition": "end; final decision"},
    "consequence": {"grade_levels": [9], "sight_word": True, "definition": "result of action"},
    "construct": {"grade_levels": [9], "sight_word": True, "definition": "to build"},
    "contrast": {"grade_levels": [9], "sight_word": True, "definition": "to show differences"},
    "criteria": {"grade_levels": [9], "sight_word": True, "definition": "standards for judging"},
    "derive": {"grade_levels": [9], "sight_word": True, "definition": "to obtain from source"},
    "dimension": {"grade_levels": [9], "sight_word": True, "definition": "measurement; aspect"},
    "distinguish": {"grade_levels": [9], "sight_word": True, "definition": "to recognize differences"},
    "evaluate": {"grade_levels": [9], "sight_word": True, "definition": "to judge the value of"},
    "evidence": {"grade_levels": [9], "sight_word": True, "definition": "proof or facts"},
    "factor": {"grade_levels": [9], "sight_word": True, "definition": "element that contributes"},
    "function": {"grade_levels": [9], "sight_word": True, "definition": "purpose; to work"},
    "identify": {"grade_levels": [9], "sight_word": True, "definition": "to recognize"},
    "impact": {"grade_levels": [9], "sight_word": True, "definition": "strong effect"},
    "imply": {"grade_levels": [9], "sight_word": True, "definition": "to suggest without stating"},
    "indicate": {"grade_levels": [9], "sight_word": True, "definition": "to point out"},
    "interpret": {"grade_levels": [9], "sight_word": True, "definition": "to explain meaning"},
    "issue": {"grade_levels": [9], "sight_word": True, "definition": "problem; topic"},
    "logical": {"grade_levels": [9], "sight_word": True, "definition": "using reason"},
    "method": {"grade_levels": [9], "sight_word": True, "definition": "way of doing something"},
    "occur": {"grade_levels": [9], "sight_word": True, "definition": "to happen"},
    "perspective": {"grade_levels": [9], "sight_word": True, "definition": "point of view"},
    "policy": {"grade_levels": [9], "sight_word": True, "definition": "course of action"},
    "principle": {"grade_levels": [9], "sight_word": True, "definition": "basic rule or belief"},
    "process": {"grade_levels": [9], "sight_word": True, "definition": "series of actions"},
    "reaction": {"grade_levels": [9], "sight_word": True, "definition": "response to something"},
    "relevant": {"grade_levels": [9], "sight_word": True, "definition": "closely connected"},
    "research": {"grade_levels": [9], "sight_word": True, "definition": "careful study"},
    "respond": {"grade_levels": [9], "sight_word": True, "definition": "to answer"},
    "role": {"grade_levels": [9], "sight_word": True, "definition": "part played by someone"},
    "section": {"grade_levels": [9], "sight_word": True, "definition": "part of something larger"},
    "significant": {"grade_levels": [9], "sight_word": True, "definition": "important; meaningful"},
    "source": {"grade_levels": [9], "sight_word": True, "definition": "origin; beginning"},
    "structure": {"grade_levels": [9], "sight_word": True, "definition": "arrangement of parts"},
    "theory": {"grade_levels": [9], "sight_word": True, "definition": "explanation based on evidence"},
    "variable": {"grade_levels": [9], "sight_word": True, "definition": "factor that can change"},
    
    # Grade 10 sight words
    "analyze": {"grade_levels": [10], "sight_word": True, "definition": "to examine in detail"},
    "anticipate": {"grade_levels": [10], "sight_word": True, "definition": "to expect or predict"},
    "approximate": {"grade_levels": [10], "sight_word": True, "definition": "close to exact; estimate"},
    "articulate": {"grade_levels": [10], "sight_word": True, "definition": "to express clearly"},
    "assess": {"grade_levels": [10], "sight_word": True, "definition": "to evaluate"},
    "assume": {"grade_levels": [10], "sight_word": True, "definition": "to suppose without proof"},
    "cite": {"grade_levels": [10], "sight_word": True, "definition": "to quote as evidence"},
    "coincide": {"grade_levels": [10], "sight_word": True, "definition": "to occur at same time"},
    "compare": {"grade_levels": [10], "sight_word": True, "definition": "to examine similarities"},
    "compose": {"grade_levels": [10], "sight_word": True, "definition": "to create; to write"},
    "concentrate": {"grade_levels": [10], "sight_word": True, "definition": "to focus attention"},
    "conclude": {"grade_levels": [10], "sight_word": True, "definition": "to end; to decide"},
    "contrast": {"grade_levels": [10], "sight_word": True, "definition": "to show differences"},
    "correspond": {"grade_levels": [10], "sight_word": True, "definition": "to match; to write letters"},
    "criteria": {"grade_levels": [10], "sight_word": True, "definition": "standards for judging"},
    "debate": {"grade_levels": [10], "sight_word": True, "definition": "formal discussion"},
    "deduce": {"grade_levels": [10], "sight_word": True, "definition": "to conclude from evidence"},
    "demonstrate": {"grade_levels": [10], "sight_word": True, "definition": "to show clearly"},
    "derive": {"grade_levels": [10], "sight_word": True, "definition": "to obtain from source"},
    "determine": {"grade_levels": [10], "sight_word": True, "definition": "to decide or find out"},
    "differentiate": {"grade_levels": [10], "sight_word": True, "definition": "to show differences"},
    "distribute": {"grade_levels": [10], "sight_word": True, "definition": "to give out"},
    "emphasize": {"grade_levels": [10], "sight_word": True, "definition": "to stress importance"},
    "evaluate": {"grade_levels": [10], "sight_word": True, "definition": "to judge the value of"},
    "examine": {"grade_levels": [10], "sight_word": True, "definition": "to look at carefully"},
    "exceed": {"grade_levels": [10], "sight_word": True, "definition": "to go beyond"},
    "explicit": {"grade_levels": [10], "sight_word": True, "definition": "clearly stated"},
    "formulate": {"grade_levels": [10], "sight_word": True, "definition": "to create or develop"},
    "hypothesis": {"grade_levels": [10], "sight_word": True, "definition": "educated guess for testing"},
    "illustrate": {"grade_levels": [10], "sight_word": True, "definition": "to show with examples"},
    "imply": {"grade_levels": [10], "sight_word": True, "definition": "to suggest without stating"},
    "infer": {"grade_levels": [10], "sight_word": True, "definition": "to conclude from evidence"},
    "integrate": {"grade_levels": [10], "sight_word": True, "definition": "to combine into whole"},
    "interpret": {"grade_levels": [10], "sight_word": True, "definition": "to explain meaning"},
    "investigate": {"grade_levels": [10], "sight_word": True, "definition": "to examine systematically"},
    "justify": {"grade_levels": [10], "sight_word": True, "definition": "to provide reasons"},
    "maintain": {"grade_levels": [10], "sight_word": True, "definition": "to keep in good condition"},
    "modify": {"grade_levels": [10], "sight_word": True, "definition": "to change slightly"},
    "outcome": {"grade_levels": [10], "sight_word": True, "definition": "result"},
    "parameter": {"grade_levels": [10], "sight_word": True, "definition": "boundary or limit"},
    "predict": {"grade_levels": [10], "sight_word": True, "definition": "to forecast"},
    "process": {"grade_levels": [10], "sight_word": True, "definition": "series of actions"},
    "proportion": {"grade_levels": [10], "sight_word": True, "definition": "comparative relation"},
    "qualitative": {"grade_levels": [10], "sight_word": True, "definition": "relating to quality"},
    "quantitative": {"grade_levels": [10], "sight_word": True, "definition": "relating to quantity"},
    "relevant": {"grade_levels": [10], "sight_word": True, "definition": "closely connected"},
    "research": {"grade_levels": [10], "sight_word": True, "definition": "careful study"},
    "significance": {"grade_levels": [10], "sight_word": True, "definition": "importance; meaning"},
    "theory": {"grade_levels": [10], "sight_word": True, "definition": "explanation based on evidence"},
    "valid": {"grade_levels": [10], "sight_word": True, "definition": "sound; acceptable"},
    
    # Grade 9 non-sight words
    "acknowledge": {"grade_levels": [9], "sight_word": False, "definition": "to admit or recognize"},
    "adaptation": {"grade_levels": [9], "sight_word": False, "definition": "change to fit environment"},
    "advocate": {"grade_levels": [9], "sight_word": False, "definition": "to support publicly"},
    "aesthetic": {"grade_levels": [9], "sight_word": False, "definition": "relating to beauty"},
    "ambiguous": {"grade_levels": [9], "sight_word": False, "definition": "having more than one meaning"},
    "anomaly": {"grade_levels": [9], "sight_word": False, "definition": "something unusual"},
    "antagonist": {"grade_levels": [9], "sight_word": False, "definition": "opponent; enemy"},
    "approximate": {"grade_levels": [9], "sight_word": False, "definition": "close to exact; estimate"},
    "articulate": {"grade_levels": [9], "sight_word": False, "definition": "to express clearly"},
    "assertion": {"grade_levels": [9], "sight_word": False, "definition": "confident statement"},
    "assumption": {"grade_levels": [9], "sight_word": False, "definition": "something accepted as true"},
    "authenticity": {"grade_levels": [9], "sight_word": False, "definition": "quality of being genuine"},
    "bias": {"grade_levels": [9], "sight_word": False, "definition": "prejudice; unfair preference"},
    "brevity": {"grade_levels": [9], "sight_word": False, "definition": "shortness; conciseness"},
    "chronological": {"grade_levels": [9], "sight_word": False, "definition": "arranged in time order"},
    "coincidence": {"grade_levels": [9], "sight_word": False, "definition": "remarkable occurrence"},
    "compromise": {"grade_levels": [9], "sight_word": False, "definition": "settlement by mutual concession"},
    "connotation": {"grade_levels": [9], "sight_word": False, "definition": "implied meaning"},
    "correlation": {"grade_levels": [9], "sight_word": False, "definition": "mutual relationship"},
    "credibility": {"grade_levels": [9], "sight_word": False, "definition": "quality of being believable"},
    "deduction": {"grade_levels": [9], "sight_word": False, "definition": "reasoning from general to specific"},
    "demonstration": {"grade_levels": [9], "sight_word": False, "definition": "showing how something works"},
    "depict": {"grade_levels": [9], "sight_word": False, "definition": "to show or describe"},
    "discrepancy": {"grade_levels": [9], "sight_word": False, "definition": "difference; inconsistency"},
    "distortion": {"grade_levels": [9], "sight_word": False, "definition": "twisting out of shape"},
    "elaboration": {"grade_levels": [9], "sight_word": False, "definition": "detailed explanation"},
    "empirical": {"grade_levels": [9], "sight_word": False, "definition": "based on observation"},
    "epiphany": {"grade_levels": [9], "sight_word": False, "definition": "sudden realization"},
    "exposition": {"grade_levels": [9], "sight_word": False, "definition": "detailed explanation"},
    "figurative": {"grade_levels": [9], "sight_word": False, "definition": "metaphorical; not literal"},
    "foreshadow": {"grade_levels": [9], "sight_word": False, "definition": "to hint at future events"},
    "helicopter": {"grade_levels": [9], "sight_word": False, "definition": "aircraft with rotating blades"},
    "implication": {"grade_levels": [9], "sight_word": False, "definition": "conclusion that can be drawn"},
    "inference": {"grade_levels": [9], "sight_word": False, "definition": "conclusion from evidence"},
    "integrate": {"grade_levels": [9], "sight_word": False, "definition": "to combine into whole"},
    "intuition": {"grade_levels": [9], "sight_word": False, "definition": "understanding without reasoning"},
    "irony": {"grade_levels": [9], "sight_word": False, "definition": "contrast between expectation and reality"},
    "juxtaposition": {"grade_levels": [9], "sight_word": False, "definition": "placing side by side"},
    "metaphor": {"grade_levels": [9], "sight_word": False, "definition": "comparison without using like or as"},
    "notion": {"grade_levels": [9], "sight_word": False, "definition": "idea or concept"},
    "objective": {"grade_levels": [9], "sight_word": False, "definition": "unbiased; goal"},
    "paradox": {"grade_levels": [9], "sight_word": False, "definition": "contradictory statement"},
    "preliminary": {"grade_levels": [9], "sight_word": False, "definition": "coming before main part"},
    "rationale": {"grade_levels": [9], "sight_word": False, "definition": "reasoning behind decision"},
    "redundant": {"grade_levels": [9], "sight_word": False, "definition": "unnecessary repetition"},
    "symbolism": {"grade_levels": [9], "sight_word": False, "definition": "use of symbols to represent ideas"},
    "transition": {"grade_levels": [9], "sight_word": False, "definition": "change from one state to another"},
    
    # Grade 10 non-sight words
    "aberration": {"grade_levels": [10], "sight_word": False, "definition": "departure from normal"},
    "abstracted": {"grade_levels": [10], "sight_word": False, "definition": "removed; theoretical"},
    "acquisition": {"grade_levels": [10], "sight_word": False, "definition": "act of gaining possession"},
    "adversity": {"grade_levels": [10], "sight_word": False, "definition": "difficult situation"},
    "allegory": {"grade_levels": [10], "sight_word": False, "definition": "story with hidden meaning"},
    "allusion": {"grade_levels": [10], "sight_word": False, "definition": "indirect reference"},
    "analytical": {"grade_levels": [10], "sight_word": False, "definition": "using logical analysis"},
    "anecdote": {"grade_levels": [10], "sight_word": False, "definition": "short amusing story"},
    "antithesis": {"grade_levels": [10], "sight_word": False, "definition": "direct opposite"},
    "arbitrary": {"grade_levels": [10], "sight_word": False, "definition": "based on random choice"},
    "assertive": {"grade_levels": [10], "sight_word": False, "definition": "confident and direct"},
    "belligerent": {"grade_levels": [10], "sight_word": False, "definition": "aggressive; hostile"},
    "benevolent": {"grade_levels": [10], "sight_word": False, "definition": "kind and generous"},
    "camaraderie": {"grade_levels": [10], "sight_word": False, "definition": "friendship among group"},
    "catalyst": {"grade_levels": [10], "sight_word": False, "definition": "agent causing change"},
    "chronology": {"grade_levels": [10], "sight_word": False, "definition": "arrangement in time order"},
    "cohesive": {"grade_levels": [10], "sight_word": False, "definition": "forming united whole"},
    "compliance": {"grade_levels": [10], "sight_word": False, "definition": "conformity with rules"},
    "condone": {"grade_levels": [10], "sight_word": False, "definition": "to accept or allow"},
    "connotation": {"grade_levels": [10], "sight_word": False, "definition": "implied meaning"},
    "convergence": {"grade_levels": [10], "sight_word": False, "definition": "coming together"},
    "credibility": {"grade_levels": [10], "sight_word": False, "definition": "quality of being believable"},
    "decipher": {"grade_levels": [10], "sight_word": False, "definition": "to decode or interpret"},
    "delineate": {"grade_levels": [10], "sight_word": False, "definition": "to describe precisely"},
    "denotation": {"grade_levels": [10], "sight_word": False, "definition": "literal meaning"},
    "detrimental": {"grade_levels": [10], "sight_word": False, "definition": "causing harm"},
    "dichotomy": {"grade_levels": [10], "sight_word": False, "definition": "division into two parts"},
    "discernment": {"grade_levels": [10], "sight_word": False, "definition": "ability to judge well"},
    "eloquence": {"grade_levels": [10], "sight_word": False, "definition": "fluent speaking or writing"},
    "empirical": {"grade_levels": [10], "sight_word": False, "definition": "based on observation"},
    "ephemeral": {"grade_levels": [10], "sight_word": False, "definition": "lasting very short time"},
    "erroneous": {"grade_levels": [10], "sight_word": False, "definition": "incorrect; mistaken"},
    "fallacy": {"grade_levels": [10], "sight_word": False, "definition": "mistaken belief"},
    "feasible": {"grade_levels": [10], "sight_word": False, "definition": "possible to do"},
    "fundamental": {"grade_levels": [10], "sight_word": False, "definition": "basic; essential"},
    "hierarchy": {"grade_levels": [10], "sight_word": False, "definition": "system of ranking"},
    "ideology": {"grade_levels": [10], "sight_word": False, "definition": "system of ideas"},
    "imperative": {"grade_levels": [10], "sight_word": False, "definition": "essential; urgent"},
    "incessant": {"grade_levels": [10], "sight_word": False, "definition": "continuing without pause"},
    "inevitable": {"grade_levels": [10], "sight_word": False, "definition": "certain to happen"},
    "meticulous": {"grade_levels": [10], "sight_word": False, "definition": "very careful and precise"},
    "negligible": {"grade_levels": [10], "sight_word": False, "definition": "so small as to be unimportant"},
    "objective": {"grade_levels": [10], "sight_word": False, "definition": "unbiased; goal"},
    "omniscient": {"grade_levels": [10], "sight_word": False, "definition": "knowing everything"},
    "paradoxical": {"grade_levels": [10], "sight_word": False, "definition": "seemingly contradictory"},
    "peripheral": {"grade_levels": [10], "sight_word": False, "definition": "on the edge; minor"},
    "pertinent": {"grade_levels": [10], "sight_word": False, "definition": "relevant; applicable"},
    "plausible": {"grade_levels": [10], "sight_word": False, "definition": "seeming reasonable"},
    "precursor": {"grade_levels": [10], "sight_word": False, "definition": "something that comes before"},
    "synthesis": {"grade_levels": [10], "sight_word": False, "definition": "combination of parts into whole"}
}